version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    user: "${UID:-1000}:${GID:-1000}"  
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "81:81"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  
  redis:
    image: redis:8-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local